# Generated by Django 2.2.3 on 2019-09-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0041_auto_20190929_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
